### ISSUE TITLE
Need udev rules for moonlander please

### ISSUE THREAD

**Issue by andyhunne** [zsa/wally#61]
Ordered my moonlander mk 1 today - would love to see this updated for the moonlander as well.

**Comment by fdidron** [comment]
Hi @andyhunne 

First many thanks for getting a Moonlander !

I updated the udev rule for Live Training. For Wally's flashing the udev rule doesn't need to change because we are using the same mcu the Planck uses.

I'm also currently updating Wally to support the Moonlander, it should be out in a couple days now. Closing this for now, feel free to reopen if you have any questions.
